### ISSUE TITLE
Link not rendering 

### ISSUE THREAD

**Issue by tomparson** [MikeKSmith/The_Lazy_Producer#47]
https://mikeksmith.github.io/The_Lazy_Producer/process---note-wise-probability.html

3.0.3 the link at the start isn’t rendering, and the link in the last sentence at the bottom is the same

**Comment by MikeKSmith** [comment]
Thanks for raising this issue. Fixing links and cross-references is something I hope to get to in the next couple of weeks.

**Comment by MikeKSmith** [comment]
Fixed in commit 6dab1d94e50ff8305cf1efdf6f6b3bf33f06a348
